### ISSUE TITLE
Fix to_parquet()

### ISSUE THREAD

**Issue by michalz92** [kfk/grizly#375]
- [ ] 1.

```
2020-04-03 11:04:50,266 - distributed.worker.account_receivable_weekly_snapshots - INFO - Writing to 2020.AERG.2.6.parquet...
```

- [ ] 2.

```
Traceback (most recent call last):
  File "/home/acoe_workflows/workflows/workflows/account_receivable_weekly_snapshots/account_receivable_weekly_snapshots.py", line 62, in qf_to_parquet
    cursor_row_count = qf.to_parquet(file_path, chunksize=chunksize, debug=True)
  File "/usr/local/lib/python3.7/site-packages/grizly-0.3.1-py3.7.egg/grizly/tools/extract.py", line 56, in to_parquet
    self.df = self.to_df()
  File "/usr/local/lib/python3.7/site-packages/grizly-0.3.1-py3.7.egg/grizly/tools/qframe.py", line 1009, in to_df
    df = read_sql(sql=sql, con=con)
  File "/usr/local/lib64/python3.7/site-packages/pandas/io/sql.py", line 410, in read_sql
    chunksize=chunksize,
  File "/usr/local/lib64/python3.7/site-packages/pandas/io/sql.py", line 1646, in read_query
    columns = [col_desc[0] for col_desc in cursor.description]
TypeError: 'NoneType' object is not iterable
'NoneType' object is not iterable,
```

**Comment by michalz92** [comment]
This was fixed back in 0.3.5 or earlier.
